"""fix learning_path_comments table and fks

Revision ID: 29e742b2dd9f
Revises: 20260119_0005
Create Date: 2026-01-21 15:03:43.509549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29e742b2dd9f'
down_revision: Union[str, Sequence[str], None] = '20260119_0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_resources_url'), table_name='link_resources')
    op.drop_table('link_resources')
    op.drop_table('user_resource')
    op.alter_column('resources', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('resources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('resources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('resources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('resources', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_table('user_resource',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('user_resource_resource_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_resource_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'resource_id', name=op.f('uq_user_resource'))
    )
    op.create_table('link_resources',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('thumbnail_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], name=op.f('link_resources_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('link_resources_pkey'))
    )
    op.create_index(op.f('ix_link_resources_url'), 'link_resources', ['url'], unique=True)
    # ### end Alembic commands ###
